basePath: /
definitions:
  admin.deleteResponse:
    properties:
      username:
        description: 用户名
        type: string
    type: object
  admin.listData:
    properties:
      created_at:
        description: 创建时间
        type: string
      created_user:
        description: 创建人
        type: string
      id:
        description: 主键ID
        type: integer
      is_used:
        description: 是否启用(1:是 -1:否)
        type: integer
      mobile:
        description: 手机号
        type: string
      nickname:
        description: 昵称
        type: string
      updated_at:
        description: 更新时间
        type: string
      updated_user:
        description: 更新人
        type: string
      username:
        description: 用户名
        type: string
    type: object
  admin.listResponse:
    properties:
      items:
        description: 当前页的数据列表
        items:
          $ref: '#/definitions/admin.listData'
        type: array
      page:
        description: 当前页码
        type: integer
      page_size:
        description: 每页返回的数据量
        type: integer
      total:
        description: 符合查询条件的总记录数
        type: integer
    type: object
  admin.loginRequest:
    properties:
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    required:
    - password
    - username
    type: object
  admin.loginResponse:
    properties:
      token:
        description: 登录成功后颁发的 Token
        type: string
      user_info:
        properties:
          created_at:
            description: 创建时间
            type: string
          created_user:
            description: 创建人
            type: string
          id:
            description: 主键ID
            type: integer
          is_used:
            description: 是否启用(1:是 -1:否)
            type: integer
          mobile:
            description: 手机号
            type: string
          nickname:
            description: 昵称
            type: string
          updated_at:
            description: 更新时间
            type: string
          updated_user:
            description: 更新人
            type: string
          username:
            description: 用户名
            type: string
        type: object
    type: object
  admin.oneResponse:
    properties:
      created_at:
        description: 创建时间
        type: string
      created_user:
        description: 创建人
        type: string
      id:
        description: 主键ID
        type: integer
      is_used:
        description: 是否启用(1:是 -1:否)
        type: integer
      mobile:
        description: 手机号
        type: string
      nickname:
        description: 昵称
        type: string
      updated_at:
        description: 更新时间
        type: string
      updated_user:
        description: 更新人
        type: string
      username:
        description: 用户名
        type: string
    type: object
  admin.registerRequest:
    properties:
      mobile:
        description: 手机号
        type: string
      nickname:
        description: 昵称
        type: string
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    required:
    - mobile
    - password
    - username
    type: object
  admin.registerResponse:
    properties:
      created_at:
        description: 创建时间
        type: string
      created_user:
        description: 创建人
        type: string
      id:
        description: 主键ID
        type: integer
      is_used:
        description: 是否启用(1:是 -1:否)
        type: integer
      mobile:
        description: 手机号
        type: string
      nickname:
        description: 昵称
        type: string
      username:
        description: 用户名
        type: string
    type: object
  admin.updateRequest:
    properties:
      is_used:
        description: 是否启用(1:是 -1:否)
        type: integer
      mobile:
        description: 手机号
        type: string
      nickname:
        description: 昵称
        type: string
      password:
        description: 密码
        type: string
    type: object
  admin.updateResponse:
    properties:
      created_at:
        description: 创建时间
        type: string
      created_user:
        description: 创建人
        type: string
      id:
        description: 主键ID
        type: integer
      is_used:
        description: 是否启用(1:是 -1:否)
        type: integer
      mobile:
        description: 手机号
        type: string
      nickname:
        description: 昵称
        type: string
      updated_at:
        description: 更新时间
        type: string
      updated_user:
        description: 更新人
        type: string
      username:
        description: 用户名
        type: string
    type: object
  code.Failure:
    properties:
      code:
        description: 业务码
        type: integer
      message:
        description: 描述信息
        type: string
    type: object
info:
  contact: {}
  title: gin-api-admin 接口文档
  version: v0.0.1
paths:
  /api/admin/{username}:
    delete:
      consumes:
      - application/json
      description: 删除管理员信息
      parameters:
      - description: 用户名
        in: path
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/admin.deleteResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/code.Failure'
      security:
      - LoginVerifyToken: []
      summary: 删除管理员信息
      tags:
      - API.admin
    get:
      consumes:
      - application/json
      description: 获取单条管理员信息
      parameters:
      - description: 用户名
        in: path
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/admin.oneResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/code.Failure'
      security:
      - LoginVerifyToken: []
      summary: 获取单条管理员信息
      tags:
      - API.admin
    put:
      consumes:
      - application/json
      description: 更新管理员信息
      parameters:
      - description: 用户名
        in: path
        name: username
        required: true
        type: string
      - description: 请求参数
        in: body
        name: RequestBody
        required: true
        schema:
          $ref: '#/definitions/admin.updateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/admin.updateResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/code.Failure'
      security:
      - LoginVerifyToken: []
      summary: 更新管理员信息
      tags:
      - API.admin
  /api/admin/login:
    post:
      consumes:
      - application/json
      description: 管理员登录
      parameters:
      - description: 请求参数
        in: body
        name: RequestBody
        required: true
        schema:
          $ref: '#/definitions/admin.loginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/admin.loginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/code.Failure'
      summary: 管理员登录
      tags:
      - API.login
  /api/admin/register:
    post:
      consumes:
      - application/json
      description: 管理员注册
      parameters:
      - description: 请求参数
        in: body
        name: RequestBody
        required: true
        schema:
          $ref: '#/definitions/admin.registerRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/admin.registerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/code.Failure'
      summary: 管理员注册
      tags:
      - API.register
  /api/admins:
    get:
      consumes:
      - application/json
      description: 获取管理员列表
      parameters:
      - default: 1
        description: 当前页码
        in: query
        name: page
        required: true
        type: integer
      - default: 20
        description: 每页返回的数据量，最多 200 条
        in: query
        name: page_size
        required: true
        type: integer
      - default: id
        description: 排序字段的名称
        in: query
        name: sort_field
        required: true
        type: string
      - default: desc
        description: 排序的顺序
        in: query
        name: sort_order
        required: true
        type: string
      - description: 用户名，支持模糊查询
        in: query
        name: username
        type: string
      - description: 昵称，支持模糊查询
        in: query
        name: nickname
        type: string
      - description: 手机号，支持模糊查询
        in: query
        name: mobile
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/admin.listResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/code.Failure'
      security:
      - LoginVerifyToken: []
      summary: 获取管理员列表
      tags:
      - API.admin
securityDefinitions:
  LoginVerifyToken:
    in: header
    name: Token
    type: apiKey
swagger: "2.0"
